
baseURL = "https://west-mountain.github.io/westblog/"
canonifyURLs = true
languageCode = "en-us"
title = "一寸相思半生孤勇"
theme = "blackburn"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2